# -*- coding: utf-8 -*-
"""gerenciador.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TAco3LDfls-72xNbB093Em4LjQtkBmC
"""

def adicionar_tarefa(tarefas, nome_tarefa="tarefa padrão"):
    tarefa = {"tarefa": nome_tarefa, "Completada": False}
    tarefas.append(tarefa)
    print(f"Tarefa '{nome_tarefa}' foi adicionada com sucesso!")


def ver_tarefas(tarefas):
    print("\nLista de Tarefas:")
    if not tarefas:
        print("Nenhuma tarefa adicionada ainda.")
        return

    for indice, tarefa in enumerate(tarefas, start=1):
        status = "✓" if tarefa["Completada"] else " "
        nome_tarefa = tarefa["tarefa"]
        print(f"{indice}. [{status}] {nome_tarefa}")


def atualizar_nome_tarefa(tarefas, indice_tarefa, novo_nome_tarefa):
    indice_tarefa_ajustado = indice_tarefa - 1

    if 0 <= indice_tarefa_ajustado < len(tarefas):
        tarefas[indice_tarefa_ajustado]["tarefa"] = novo_nome_tarefa
        print(f"Tarefa {indice_tarefa} atualizada para '{novo_nome_tarefa}'.")
    else:
        print("Índice de tarefa inválido.")


def completar_tarefa(tarefas, indice_tarefa):
    indice_tarefa_ajustado = indice_tarefa - 1

    if 0 <= indice_tarefa_ajustado < len(tarefas):
        tarefas[indice_tarefa_ajustado]["Completada"] = True
        print(f"Tarefa {indice_tarefa} marcada como completada.")
    else:
        print("Índice de tarefa inválido.")


def deletar_tarefas_completadas(tarefas):
    if not tarefas:
        print("Nenhuma tarefa para deletar.")
        return

    tarefas[:] = [tarefa for tarefa in tarefas if not tarefa["Completada"]]
    print("Todas as tarefas completadas foram deletadas com sucesso!")


tarefas = []

while True:
    print("\nMenu do Gerenciador de Listas de Tarefas")
    print("1. Adicionar tarefas")
    print("2. Ver tarefas")
    print("3. Atualizar tarefas")
    print("4. Completar tarefas")
    print("5. Deletar tarefas completadas")
    print("6. Sair")

    escolha = input("Digite a sua escolha: ")

    if escolha == "1":
        nome_tarefa = input("Digite o nome da tarefa: ")
        adicionar_tarefa(tarefas, nome_tarefa)

    elif escolha == "2":
        ver_tarefas(tarefas)

    elif escolha == "3":
        ver_tarefas(tarefas)
        indice = int(input("Digite o número da tarefa que deseja atualizar: "))
        novo_nome = input("Digite o novo nome da tarefa: ")
        atualizar_nome_tarefa(tarefas, indice, novo_nome)

    elif escolha == "4":
        ver_tarefas(tarefas)
        indice = int(input("Digite o número da tarefa que deseja completar: "))
        completar_tarefa(tarefas, indice)

    elif escolha == "5":
        deletar_tarefas_completadas(tarefas)
        ver_tarefas(tarefas)

    elif escolha == "6":
        print("Programa Finalizado")
        break

    else:
        print("Opção inválida. Tente novamente.")